// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
    name,
    latitude,
    longitude,
    location_name
) VALUES ($1, $2, $3, $4) RETURNING id, name, latitude, longitude, location_name, created_at, updated_at
`

type CreateCompanyParams struct {
	Name         string        `json:"name"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
	LocationName pgtype.Text   `json:"location_name"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.LocationName,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :one
DELETE FROM companies WHERE id = $1 RETURNING id, name, latitude, longitude, location_name, created_at, updated_at
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, deleteCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, latitude, longitude, location_name, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, latitude, longitude, location_name, created_at, updated_at FROM companies ORDER BY created_at DESC
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.LocationName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = COALESCE(NULLIF($1, name), name),
    latitude = COALESCE($2, latitude),
    longitude = COALESCE($3, longitude),
    location_name = COALESCE(NULLIF($4, location_name), location_name)
WHERE id = $5 RETURNING id, name, latitude, longitude, location_name, created_at, updated_at
`

type UpdateCompanyParams struct {
	Name         string        `json:"name"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
	LocationName pgtype.Text   `json:"location_name"`
	ID           uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.LocationName,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
