// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                uuid.UUID          `json:"id"`
	FirstName         string             `json:"first_name"`
	MiddleName        string             `json:"middle_name"`
	LastName          string             `json:"last_name"`
	Username          string             `json:"username"`
	Password          string             `json:"password"`
	Phone             string             `json:"phone"`
	Email             string             `json:"email"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Video struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Bucket        string             `json:"bucket"`
	Key           string             `json:"key"`
	Status        string             `json:"status"`
	FileSizeBytes int64              `json:"file_size_bytes"`
	ContentType   string             `json:"content_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type VideoVariant struct {
	ID             uuid.UUID          `json:"id"`
	VideoID        uuid.UUID          `json:"video_id"`
	VariantName    string             `json:"variant_name"`
	Bucket         string             `json:"bucket"`
	Key            string             `json:"key"`
	ContentType    string             `json:"content_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	HlsPlaylistKey pgtype.Text        `json:"hls_playlist_key"`
	ThumbnailKey   pgtype.Text        `json:"thumbnail_key"`
	Width          pgtype.Int4        `json:"width"`
	Height         pgtype.Int4        `json:"height"`
	BitrateKbps    pgtype.Int4        `json:"bitrate_kbps"`
}
