// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OriginalVideo struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	Status        string    `json:"status"`
	Filename      string    `json:"filename"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Bucket        string    `json:"bucket"`
	Key           string    `json:"key"`
	FileSizeBytes int64     `json:"file_size_bytes"`
	ContentType   string    `json:"content_type"`
	Duration      int32     `json:"duration"`
	Width         int32     `json:"width"`
	Height        int32     `json:"height"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ProcessedVideo struct {
	ID            uuid.UUID `json:"id"`
	VideoID       uuid.UUID `json:"video_id"`
	ContentType   string    `json:"content_type"`
	Bucket        string    `json:"bucket"`
	Key           string    `json:"key"`
	Width         int32     `json:"width"`
	Height        int32     `json:"height"`
	FileSizeBytes int64     `json:"file_size_bytes"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	FirstName         string             `json:"first_name"`
	MiddleName        string             `json:"middle_name"`
	LastName          string             `json:"last_name"`
	Username          string             `json:"username"`
	Password          string             `json:"password"`
	Phone             string             `json:"phone"`
	Email             string             `json:"email"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}
