// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    middle_name,
    last_name,
    phone,
    username,
    password,
    email
) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, first_name, middle_name, last_name, username, password, phone, email, profile_picture_url, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	FirstName  string `json:"first_name"`
	MiddleName string `json:"middle_name"`
	LastName   string `json:"last_name"`
	Phone      string `json:"phone"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	Email      string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Phone,
		arg.Username,
		arg.Password,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Phone,
		&i.Email,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1 RETURNING id, first_name, middle_name, last_name, username, password, phone, email, profile_picture_url, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Phone,
		&i.Email,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, middle_name, last_name, username, password, phone, email, profile_picture_url, created_at, updated_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Phone,
		&i.Email,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, middle_name, last_name, username, password, phone, email, profile_picture_url, created_at, updated_at, deleted_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Phone,
		&i.Email,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, first_name, middle_name, last_name, username, password, phone, email, profile_picture_url, created_at, updated_at, deleted_at FROM users WHERE first_name ILIKE $1 
OR last_name ILIKE $1 
OR username ILIKE $1 
OR email ILIKE $1 
OR phone ILIKE $1
`

func (q *Queries) SearchUsers(ctx context.Context, firstName string) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, firstName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.Username,
			&i.Password,
			&i.Phone,
			&i.Email,
			&i.ProfilePictureUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = COALESCE(NULLIF($1, first_name), first_name),
    middle_name=COALESCE(NULLIF($2, middle_name), middle_name),
    last_name = COALESCE(NULLIF($3, last_name), last_name),
    phone = COALESCE(NULLIF($4, phone), phone),
    username = COALESCE(NULLIF($5, username), username),
    email = COALESCE(NULLIF($6, email), email)
WHERE id = $7 RETURNING id, first_name, middle_name, last_name, username, password, phone, email, profile_picture_url, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	FirstName  string    `json:"first_name"`
	MiddleName string    `json:"middle_name"`
	LastName   string    `json:"last_name"`
	Phone      string    `json:"phone"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Phone,
		arg.Username,
		arg.Email,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Phone,
		&i.Email,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
