// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    user_id,     
    title,
    description,
    bucket,
    key,
    file_size_bytes,
    content_type
) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, title, description, bucket, key, status, file_size_bytes, content_type, created_at, updated_at
`

type CreateVideoParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Bucket        string    `json:"bucket"`
	Key           string    `json:"key"`
	FileSizeBytes int64     `json:"file_size_bytes"`
	ContentType   string    `json:"content_type"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Bucket,
		arg.Key,
		arg.FileSizeBytes,
		arg.ContentType,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Bucket,
		&i.Key,
		&i.Status,
		&i.FileSizeBytes,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :one
DELETE FROM videos WHERE id = $1 RETURNING id, user_id, title, description, bucket, key, status, file_size_bytes, content_type, created_at, updated_at
`

func (q *Queries) DeleteVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, deleteVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Bucket,
		&i.Key,
		&i.Status,
		&i.FileSizeBytes,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, user_id, title, description, bucket, key, status, file_size_bytes, content_type, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Bucket,
		&i.Key,
		&i.Status,
		&i.FileSizeBytes,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, user_id, title, description, bucket, key, status, file_size_bytes, content_type, created_at, updated_at FROM videos ORDER BY created_at DESC
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Bucket,
			&i.Key,
			&i.Status,
			&i.FileSizeBytes,
			&i.ContentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveProcessedVideoMetadata = `-- name: SaveProcessedVideoMetadata :one
INSERT INTO video_variants (
    video_id,
    variant_name,
    bucket,
    key,
    content_type,
    hls_playlist_key,
    thumbnail_key,
    width,
    height,
    bitrate_kbps
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) 
ON CONFLICT (video_id, variant_name) 
DO UPDATE SET 
    bucket = EXCLUDED.bucket,
    key = EXCLUDED.key,
    content_type = EXCLUDED.content_type,
    hls_playlist_key = EXCLUDED.hls_playlist_key,
    thumbnail_key = EXCLUDED.thumbnail_key,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    bitrate_kbps = EXCLUDED.bitrate_kbps
RETURNING id, video_id, variant_name, bucket, key, content_type, created_at, hls_playlist_key, thumbnail_key, width, height, bitrate_kbps
`

type SaveProcessedVideoMetadataParams struct {
	VideoID        uuid.UUID   `json:"video_id"`
	VariantName    string      `json:"variant_name"`
	Bucket         string      `json:"bucket"`
	Key            string      `json:"key"`
	ContentType    string      `json:"content_type"`
	HlsPlaylistKey pgtype.Text `json:"hls_playlist_key"`
	ThumbnailKey   pgtype.Text `json:"thumbnail_key"`
	Width          pgtype.Int4 `json:"width"`
	Height         pgtype.Int4 `json:"height"`
	BitrateKbps    pgtype.Int4 `json:"bitrate_kbps"`
}

func (q *Queries) SaveProcessedVideoMetadata(ctx context.Context, arg SaveProcessedVideoMetadataParams) (VideoVariant, error) {
	row := q.db.QueryRow(ctx, saveProcessedVideoMetadata,
		arg.VideoID,
		arg.VariantName,
		arg.Bucket,
		arg.Key,
		arg.ContentType,
		arg.HlsPlaylistKey,
		arg.ThumbnailKey,
		arg.Width,
		arg.Height,
		arg.BitrateKbps,
	)
	var i VideoVariant
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.VariantName,
		&i.Bucket,
		&i.Key,
		&i.ContentType,
		&i.CreatedAt,
		&i.HlsPlaylistKey,
		&i.ThumbnailKey,
		&i.Width,
		&i.Height,
		&i.BitrateKbps,
	)
	return i, err
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos
SET 
    title = COALESCE(NULLIF($1, ''), title),
    description = COALESCE(NULLIF($2, ''), description),
    bucket = COALESCE(NULLIF($3, ''), bucket),
    key = COALESCE(NULLIF($4, ''), key),
    file_size_bytes = COALESCE(NULLIF($5, 0), file_size_bytes),
    content_type = COALESCE(NULLIF($6, ''), content_type)
WHERE id = $1 RETURNING id, user_id, title, description, bucket, key, status, file_size_bytes, content_type, created_at, updated_at
`

type UpdateVideoParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Column6 interface{} `json:"column_6"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Bucket,
		&i.Key,
		&i.Status,
		&i.FileSizeBytes,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :one
UPDATE videos
SET 
    status = $1
WHERE id = $2 RETURNING id, user_id, title, description, bucket, key, status, file_size_bytes, content_type, created_at, updated_at
`

type UpdateVideoStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideoStatus, arg.Status, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Bucket,
		&i.Key,
		&i.Status,
		&i.FileSizeBytes,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
